name: Build and Publish Wasm OCI
on:
  push:
    tags:
      - 'v*' # 当你推送 v1.0 等标签时触发
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # 1. 配置 Rust 环境
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2 # 或者 wasm32-wasip2
      # 2. 编译项目 (解决你之前的依赖问题)
      - name: Build Wasm
        run: cargo build --target wasm32-wasip2 --release
      # 3. 登录到 GitHub Container Registry
      - name: Prepare Wasm binary for Docker
        run: |
          # 自动去 target 目录找到刚刚编译出来的 .wasm 文件
          # 将其复制到根目录，并统一命名为 main.wasm
          cp target/wasm32-wasip2/release/*.wasm ./main.wasm
          # 满足 crun 的 OCI 安全标准，赋予执行权限！
          chmod +x ./main.wasm
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # 4. 设置 Docker Buildx (支持 wasi/wasm 平台标记)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # 5. 构建并推送 OCI 镜像
      - name: Build and push OCI image
        uses: docker/build-push-action@v5
        with:
          context: .
          # 关键：指定平台为 wasi/wasm，这样 K3s 才能正确识别
          platforms: wasi/wasm
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          file: ./Dockerfile
